packages:
  - apps/*
  - packages/*

catalog:
  '@hookform/resolvers': ^5.2.2
  '@t3-oss/env-core': ^0.13.8
  '@tanstack/react-query': ^5.90.2
  '@types/node': ^22.18.8
  '@types/react': ^19.2.0
  '@types/react-dom': ^19.2.0
  drizzle-orm: ^0.44.6
  lucide-react: ^0.544.0
  react: ^19.2.0
  react-dom: ^19.2.0
  react-hook-form: ^7.64.0
  tailwindcss: ^4.1.14
  typescript: 5.9.3
  vitest: ^3.2.4
  vitest-mock-extended: ^3.1.0
  zod: ^4.1.11
