packages:
  - apps/*
  - packages/*

catalog:
  '@hookform/resolvers': ^5.2.2
  '@t3-oss/env-core': ^0.13.8
  '@tanstack/react-query': ^5.90.5
  '@types/node': ^22.18.13
  '@types/react': ^19.2.2
  '@types/react-dom': ^19.2.2
  drizzle-orm: ^0.44.7
  lucide-react: ^0.548.0
  react: ^19.2.0
  react-dom: ^19.2.0
  react-hook-form: ^7.65.0
  tailwindcss: ^4.1.16
  typescript: 5.9.3
  vitest: ^4.0.5
  vitest-mock-extended: ^3.1.0
  zod: ^4.1.12
