packages:
  - apps/*
  - packages/*

catalog:
  '@hookform/resolvers': ^5.2.2
  '@t3-oss/env-core': ^0.13.10
  '@tailwindcss/postcss': ^4.1.18
  '@tanstack/react-query': ^5.90.16
  '@types/node': ^22.19.3
  '@types/react': ^19.2.7
  '@types/react-dom': ^19.2.3
  drizzle-orm: ^0.45.1
  lucide-react: ^0.562.0
  react: ^19.2.3
  react-dom: ^19.2.3
  react-hook-form: ^7.69.0
  tailwindcss: ^4.1.18
  typescript: 5.9.3
  vitest: ^4.0.16
  vitest-mock-extended: ^3.1.0
  zod: ^4.3.4
