import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import "@repo/ui/global.css";
import { Providers } from "@/components/providers";
import { CheckUserOnboarding } from "@/features/user-profile/ui/check-user-onboarding";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Clerk Next.js Quickstart",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} background-background min-h-full antialiased`}
        suppressHydrationWarning
      >
        <Providers>
          <div className="flex min-h-screen bg-background">
            <CheckUserOnboarding>{children}</CheckUserOnboarding>
          </div>
        </Providers>
      </body>
    </html>
  );
}
