import type { Metadata } from "next";

import { SignedInLayout } from "@/components/signed-in-layout";

export const metadata: Metadata = {
  title: "Clerk Next.js Quickstart",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <SignedInLayout>{children}</SignedInLayout>;
}
